README.md

- Add a section for how to get started with Open Source(OS)

docs: add a section for getting started with OS

---

README.md

Readme file is improved. Important headings are highlighted and some images are added.
Repo stats badges are added as mentioned.

Readme improved and repo-stats added. 

---

README.md
src/App.js

- I fixed the condition causing that error and now the server is working fine.
- Also I updated and improved readme to contain the contributors of the project. #10 
- Also added hacktoberfest participation section for everyone to see.

fix compilation error and update readme

---

index.html
src/App.jsx
src/components/AnimatedButton.jsx
src/components/ImgUpload.jsx
src/components/Loader.css
src/components/Loader.jsx

UX: added loading animations

---

package-lock.json
src/App.jsx

This PR is related to  issue #5

logo feature added

---

src/components/Post.jsx
src/index.css

Fix:Post without image Issue with cards [Fixes #39]

---

src/components/ImgUpload.jsx

Now the upload button comes to original state as the upload completes with or without image.

Fix : Upload button loading after upload completes 

---

src/components/ImgUpload.jsx

bug : fix empty uploads and show progress bar while uploading only

---

package-lock.json
package.json
src/App.jsx
src/index.css

Added Scroll to top option once scroll down

---

package-lock.json
src/components/Post.jsx
src/index.css
src/lib/firebase.js

Feature: Post Delete

---

package-lock.json
package.json
src/components/ImgUpload.jsx
src/components/Post.jsx
src/index.css
src/lib/firebase.js

feat: use image thumbnails when loading posts

---

src/components/Post.jsx

Added like-color toggle feature

---

src/components/Post.jsx

This reverts commit f7c7066156d1258b8c89e061ffbdbc67471bc7f0, reversing changes made to 20cf6cf2420d35ca22f2a40e6a3fc283d7a5f17d.

Revert "Merge pull request #86 from bhoopesh369/bhoopesh"

---

src/components/Post.jsx

Hey i have solved the bug @narayan954 
Now you can merge the PR

Bugs resolved  Like Colour toggle feature implemented

---

index.html
src/components/Post.jsx

production was failing without any reason so reverted and pushing again

applied like color-toggle again

---

package-lock.json
package.json
src/components/Post.jsx
src/index.css

Users can now add emojis in comments using an emoji picker.
The library used for this is [emoji-picker-react](https://www.npmjs.com/package/emoji-picker-react)
Fixes #90 
Please delete options that are not relevant.

Added emoji picker in post comments

---

src/index.css

Issue no.: #93
I have added the custom scrollbar thumb.

Custom Scroll Bar

---

index.html
src/index.css
src/script.js

ISSUE NO.: #95 
I have added light and dark scrollbars according to the toggle used.
https://user-images.githubusercontent.com/103804567/198186931-b4308900-2e85-431f-b7f9-6211c1fbb0c3.mov

Dark mode Scrollbar

---

package-lock.json
src/components/Post.jsx

I Have implemmented the feature . @narayan954  @narayansoni 
Thank you!!

Bugs fixed , Deleting comments feature added

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
firebase.json
package-lock.json
package.json
src/components/ImgUpload.jsx
src/components/Post.jsx
src/script.js

Commented unused icons, refactored and formatted code, updated documentations

hid unused icons, refactored, update documentation

---

src/components/Post.jsx
src/reusableComponents/ImageSlider.css
src/reusableComponents/ImageSlider.jsx

Added Image slider in Comment Box

---

src/App.jsx
src/components/ImgUpload.jsx

This solves the issue #124 , also while signing up i.e. creating a new user the upload profile pic was also accepting any format soo corrected that too in the same PR

Allowing only images to be uploaded

---

src/App.jsx

Scroll to the top of the page onClick of logo
https://user-images.githubusercontent.com/91470808/208977665-5e0d25d2-279a-41bd-8a72-233e2d3ee502.mp4
closes #140

Scroll to the top of the page onClick of logo

---

src/index.css
src/script.js

I have fixed the problem of scrollTop occupying the entire width of the page and hence overlapping with other elements.
Also reverted the changes where we moved dark mode button upwards.
Closes #119

Fixed scrollTop button

---

index.html
src/index.css
src/script.js

Made the main page responsive

---

package-lock.json
src/App.jsx
src/index.css

#180 changed opacity and and changed color to #777 which is visible for both light and dark mode

made scroll to top button more visible

---

src/App.jsx

@narayan954 please review and merge my pr.

[FEATURE] Added profile feature in signup modal

---

src/index.css

colour of the background and  border are being changed

Updated the css file

---

src/App.jsx

@narayan954 I have implemented a new Logout Modal. Please review and merge my pr

added new logout modal

---

src/App.jsx

@narayan954 please review and merge my pr.

updated button style

---

src/App.jsx
src/components/ImgUpload.jsx
src/components/Post.jsx
src/index.css
src/reusableComponents/DialogBox.jsx
src/script.js

Closes #182 [`Theme Mode`]

---

src/index.css

@narayansoni  Please review my code

Modified index.css file

---

.github/PULL_REQUEST_TEMPLATE/NEW_PULL_REQUEST_TEMPLATE.md

Pull Request Template

---

package-lock.json
package.json
src/index.css
src/pages/Signup.jsx

The signup page looks enhanced

Signup page look enhansed

---

README.md
cypress/e2e/spec.cy.js
package.json

Closes #235 [`README`]

---

src/components/ImgUpload.jsx

Updated the "new post" section

updated new post section

---

src/App.jsx
src/pages/Profile.jsx

Added User Profile

---

src/App.jsx

Added `add post` icon in new post button

---

src/components/Post.jsx

Hi, I have changed the Ui as per the request
Closes #292 
Old Preview : 
New Preview after Changes : 
Changes Made are :
1. No new additions or deletion in code -> only shifted few lines up and down as per the request to put like, share and view comment box after the post comment box

[FIXED] likes and comment box down side of comment

---

.github/workflows/assigner.yml

disabled assigner action to prevent unregulated use / misuse

disabled assigner action

---

package-lock.json
package.json
src/App.jsx

Hey 
I fixed this issue where on Clicking this profile panel box remains open.
But now it will automatically close if the user clicks outside that panel.
Please merge my Pull request.
Thank You

Fixed Issue of Outside Clicking on Opening Profile Panel

---

src/App.jsx
src/index.css

Solved the issue of responsiveness for all devices #306

Solved the responsiveness for all devices #306

---

src/components/Post.jsx

like and share buttons are now visible in case of no comments which was not visible before.
Issue #332

like and share button are visible in case of no comments

---

src/App.jsx
src/components/Post.jsx
src/pages/Profile.jsx

Issue Solved #308 
You can now show different post-owner profiles.
@narayan954  Hey, can you review it? You can see here👇 what I have done.
https://github.com/narayan954/dummygram/assets/94003231/448fa3e8-74eb-4761-a0cf-90d92a5ada1b

Feature Addition

---

src/components/Post.jsx

Issue #319 
emoji box is now collapsing on clicking outside of the post. Initially, it was not collapsing.

emoji box collapsing on clicking outside post

---

src/components/Post.jsx
src/reusableComponents/DialogBox.jsx

I sync comment box background color with dark mode, whenever user enable dark mode the comment box will get dark also

improvement in commentbox, sync with dark mode

---

src/index.css
src/pages/Login.css
src/pages/Login.jsx
src/pages/Signup.jsx

changed the mouse pointer behavior when hovered and focused on input elements in login form.

changed input element properties

---

src/App.jsx

fixes #367 
So i have added a cross on create new posts which closes the current window
[scrnli_27_05_2023_23-53-33.webm](https://github.com/narayan954/dummygram/assets/92094765/999b332c-447a-4e6f-b849-e75f144661e0)

#367-added close button on new posts

---

src/pages/Profile.jsx

Back button is added to profile

---

src/App.jsx

Changed styles of the submenu of navbar which works with both light and dark mode. Also made changes in the alignment.

css changes to submenu of navbar

---

src/components/Post.jsx

- This PR is intended for the Emoji button on `Post.jsx` file
- Added `cursor: pointer` inline style with code linting principles
- This PR fixed this ISSUE: #395

💡 [ADD]: CURSOR POINTER FOR EMOJI BUTTON

---

package-lock.json
package.json
src/components/Post.jsx

Added the download and view profile option to all posts by clicking on the three dots. On the firebase cors.json is setup for the download of images to happen.

Added Download and view profile to three dots button

---

src/components/Post.jsx

- The user can confirm whether they want to delete a comment or not. This way, they won't accidentally delete a comment. 
- Bugs Fixed

New Feature: Confirmation for deleting a comment with bug fixes. Follow up PR of #295

---

src/pages/Profile.jsx

Made changes in the profile section

---

src/index.css

I have added a hover effect which will ease out kind on effect on hovering.
fixes #415 
[scrnli_03_06_2023_16-18-39.webm](https://github.com/narayan954/dummygram/assets/92094765/21152b4d-cd57-4cd1-b626-3f825ccfaf82)

#415-improving card items

---

src/components/Post.jsx

Issue reference - #377 
Color of delete button is changed

Delete button color is changed

---

src/components/Post.jsx
src/index.css

assigned issue number: #399 
without hover :
On hovering:
also on hoving, the curser becomes a pointer. that is we can't able to see that in the screenshot

added hover effect in emogi icon

---

src/components/Post.jsx
src/index.css

Resolved Issue-Number-348
Text Entered by User will be sent as it is to backend and fetched by preserving Line Breaks
Please merge my pull request

Text Entered by User Should be Line breaked as it is he entered

---

src/App.jsx

cancel button added
before 
after

fixed [#446]

---

src/App.jsx
src/components/Camera.jsx
src/pages/Profile.jsx

I had altered the fonts on the profile and on some links to make the font consistent across website.
Fixes issue #456

Make the font consistent across the website

---

src/App.jsx
src/components/ImgUpload.jsx
src/components/SideBar.css
src/components/SideBar.jsx
src/index.css

This is how creating new posts look like now
This is how when new post with caption & Image uploaded
@narayan954 Plz merge my pull request !!

Post Uploading Criteria Changed Completely

---

src/index.css

This PR fixes issue no. #460 
https://github.com/narayan954/dummygram/assets/116902573/37e6ee3f-f428-4626-a57b-b01aac958481

Fix home layout that was messing up with sidebar

---

src/components/Post.jsx
src/reusableComponents/ImageSlider.jsx

This PR closes the issue no. #464 . In this I have added the feature that whenever a person double click on post it get liked automatically.

Add double click to like feature #464

---

src/reusableComponents/ImageSlider.css

fixes #484 
fixed by adding cursor pointer to it now after hover it changes to pointer

fixed[#484]

---

src/components/SideBar/index.css

Hey @narayan954 I have added dark mode in sidebar. Please review my pr and merge it. Thank you!
- Issue no. #272

Added dark mode in sidebar

---

.github/workflows/linting.yml

Closes #509 
- Added the prettier linter to ensure proper and uniform linting of the codebase.
- For the linter to run successfully please open the settings of the repo go to Actions -> General -> workflow permissions and enable read and write permissions.

Added prettier linter workflow

---

.github/workflows/close_old_issues.yaml

#511 Bot added

---

src/components/Post/index.jsx

Resolved issue no. #293 
Added double tap like option for text posts too.

Double tap likes bug resolved

---

src/pages/Profile/index.css
src/pages/Profile/index.jsx

This PR closes issue no. #481 
There occured some errors in the previous branch. I created this new branch and added the feed without the use of context as you said and it works fine.

Add profile feed section

---

src/components/Post/index.jsx

Resolved Download text posts bug

---

.github/workflows/codeql.yml

* Closes - #518 
I have added the CodeQL workflow for security checks in the code.
Also comments have been added at appropriate lines to make the code understandable.

Added codeql.yml workflow

---

src/components/ImgUpload/index.css

Resolves issue #503 
Fixed text size to maintain consistency of the page.
Before:
Now:
@narayan954 *Please review this PR.*

Fixed text size

---

src/App.jsx

Closes : #507 
Before : 
After changes :

fixed: alignment of signup div

---

src/App.jsx
src/components/Navbar/index.jsx
src/pages/Profile/index.jsx

Fixes #496 - null value during destructuring location state on profile page opening from address bar and prevents application from navigating back to home page on every hard refresh.

#496: Profile page issue

---

src/App.jsx
src/components/SideBar/index.css

Hey @narayan954 I have added the lazy loading to the website. It will enhance the user experience. Please review my pr and merge it. Thank you!

Added Lazy loading

---

src/components/Navbar/index.css
src/components/Navbar/index.jsx
src/index.css
src/reusableComponents/Darkmode/Darkmode.jsx

Added Neon Logo to DummyGram

---

src/pages/Login/index.jsx
src/pages/Signup/index.css
src/pages/Signup/index.jsx
src/reusableComponents/validation.js

Added inline validation in signup and login forms.
https://github.com/narayan954/dummygram/assets/86224794/2be2798b-5338-4b57-8645-b98d53b0ac99

Inline validation in signup and login

---

src/components/Favorite.jsx

This PR closes issue no. #562 
Implemented a loader for favorite page. First, the database is checked, until then loader is shown. If there are no favorite posts then, it will show `You have nothing in favourites` else show the posts.

Set loader for favourites page

---

src/components/ImgUpload/Camera/index.css
src/components/ImgUpload/Camera/index.jsx
src/components/ImgUpload/index.css
src/components/ImgUpload/index.jsx
src/components/SideBar/index.css
src/components/SideBar/index.jsx
src/reusableComponents/Popup/index.css

Hi, Plz have a look on New Mobile and Tablet UI
Issue Number 476
Plz merge my pull request as a GSSOC'23 Contributor

New Post UI Created and Responsiveness Added

---

package-lock.json
package.json
src/App.jsx
src/components/SideBar/Footer.jsx
src/pages/Feedback/index.css
src/pages/Feedback/index.jsx
src/pages/index.js

This PR closes issue no. #417 
Added a feedback page using email js. Can you please check your gmail for the feedback mail.

Add feedback page using email js library

---

src/components/SettingsComponents/Sidebar/index.jsx
src/components/SettingsComponents/Sounds/index.css
src/components/SettingsComponents/Sounds/index.jsx
src/pages/Settings/index.jsx

#677 Close Icon 
Close issue #677 
I have successfully added close icon to setting-page.

closeIcon in setting-page

---

src/components/SideBar/index.css
src/components/SideBar/index.jsx
src/index.css

This PR closes issue no. #659 
Added scrollbar to sidebar so that the content can be accessed even on small height devices.

add scrollbar to sidebar

---

src/components/SettingsComponents/Sidebar/index.css
src/components/SettingsComponents/Sidebar/index.jsx

#685 Sidebar icon
close #685 
Icon added in setting page sidebar.

setting page sidebar icon

---

src/reusableComponents/validation.js

Resolved issue number #701 
There is only @gmail.com is allowed in mail but there are more other mail id domain so i resolved and tested it.
https://github.com/narayan954/dummygram/assets/114489502/676c16cb-f096-4e80-95bc-a44e1cad24ba

Resolved email regrex

---

src/pages/FooterPages/ContributorPage/index.jsx

solves #697 
https://github.com/narayan954/dummygram/assets/94003231/4b40e54b-bad6-4a52-b7d0-33cbabd46a5d

Add pagination in contributors page

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/docs.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/other.yml

Added the imp checkboxes

---

src/components/SearchBar/index.jsx
src/pages/Profile/index.css

#702  sidebar page menu
close #702 
Resolve the issue of sidebar in search page and horizontal line in profile page.

corrected sidebar in search page

---

src/components/SideBar/index.css
src/components/SideBar/index.jsx
src/index.css
src/pages/Profile/index.jsx
src/script.js

bug fix for sidebar active Tabs #750
@narayansoni can you please check and merge my pr

bug fix for sidebar active Tabs #750

---

src/reusableComponents/Loader/index.css
src/reusableComponents/Loader/index.jsx

Initially, the loader spinner was at the top of the page. So this pr positions the loader spinner to the center of the page.

Positioned loader spinner to center of the page

---

src/components/Post/CommentBox.jsx
src/components/Post/CommentDialogBox.jsx
src/components/SideBar/index.css

Decreased x padding of sidebar links

---

src/index.css
src/pages/Login/index.css
src/pages/Signup/index.css
src/pages/Signup/index.jsx
src/reusableComponents/Auth/Auth_container.jsx

I have updated the ui of buttons as well as for form, also, I have done it for both signIn and signUp form in dark and light mode both. Hope you like it @narayan954 
Issue reference to : https://github.com/narayan954/dummygram/issues/799
https://github.com/narayan954/dummygram/issues/800

Improvement in form ui + buttons for signup and login form both

---

src/components/postView/index.jsx
src/index.css
src/pages/PostView/PostViewStyled.jsx
src/pages/PostView/index.jsx

Closes: #789 
| | |
|---|----|
| Before | Updated |
| <img width="602" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/0024f322-bcbd-4e75-b391-2b7735759dda"> | <img width="600" src="https://github.com/narayan954/dummygram/assets/66116440/d4ba947f-f689-4c16-bec3-6261b22738df"> |
|<img width="600" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/739ad4c1-c993-4f7b-995d-07c33890892c"> | <img width="600" src="https://github.com/narayan954/dummygram/assets/66116440/e2fcd06a-b9e3-45c8-9cc8-2d00ad30053f"> |
|<img width="600" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/4ba8237a-ef1c-4b8b-bb77-4173eb9c31dd"> | <img width="600" src="https://github.com/narayan954/dummygram/assets/66116440/700aa33d-9083-4d9c-b749-2d190fb8935 …

added sidebar in post page

---

src/index.css
src/pages/Signup/index.jsx
src/reusableComponents/Auth/Auth_container.jsx
src/reusableComponents/validation.js

solves #695 
Fixed: 
confirm  password and password validation issue and adding a scroll option on the signUp page
https://github.com/narayan954/dummygram/assets/94003231/051e09be-d048-4bc8-b3e7-31336864b01e

Improve signup page and fix validation issue

---

src/App.jsx
src/components/Navbar/index.css
src/components/Navbar/index.jsx
src/index.css
src/pages/Login/index.jsx
src/pages/Profile/index.css
src/pages/Signup/index.jsx
src/reusableComponents/Auth/Auth__top.jsx
src/reusableComponents/Auth/index.js
src/reusableComponents/Logo/index.css
src/reusableComponents/Logo/index.jsx
src/reusableComponents/index.js

This PR closes issue no. #820 
Added a blue tint and a little design to logo. I created a new component for it as it is getting used in about 4 places.

Modified dummygram logo

---

src/components/postView/index.jsx
src/index.css
src/pages/PostView/PostViewStyled.jsx

comment ui

---

src/App.jsx
src/index.css
src/reusableComponents/Darkmode/index.css

fixed alignment of upward arrow

---

src/components/postView/index.jsx

fixed comment post icon

---

src/App.jsx
src/components/Navbar/index.css
src/components/Navbar/index.jsx
src/index.css
src/reusableComponents/Darkmode/index.css
src/reusableComponents/Darkmode/index.jsx

theme-bug-647 theme button change

---

src/App.jsx
src/components/Guest/GuestSignInBtn/index.css
src/components/Guest/GuestSignInBtn/index.jsx
src/components/Guest/GuestSignUpBtn/index.css
src/components/Guest/GuestSignUpBtn/index.jsx
src/components/Post/CommentBox.jsx
src/components/Post/CommentDialogBox.jsx
src/components/Post/PostHeader.jsx
src/components/Post/PostNav.jsx
src/components/SideBar/index.jsx
src/components/index.js
src/pages/Login/index.css
src/pages/Login/index.jsx
src/pages/Profile/index.jsx
src/reusableComponents/Auth/Auth__ctn__group.jsx

This PR closes issue no. #521 
I have added the guest sign in feature to it and also make sure that user will not be able to use anything other than visiting the site.

Implement guest in for dummygram

---

src/reusableComponents/Darkmode/index.css

themebutton fix : center icon #890

center themebtn icon

---

src/components/Post/PostHeader.jsx
src/components/Post/index.jsx
src/components/ProfileDialogBox/index.jsx
src/components/SideBar/index.jsx
src/pages/Profile/index.jsx

Closes: #604 
- Profile avatar displaying the updated image immediately after saving it.
- Profile modal displaying the selected image preview.
- Ensured that the updated profile image is displayed in the post, feed and sidebar.
https://github.com/narayan954/dummygram/assets/66116440/1966cf55-77f9-4111-831d-dfc95616d236

Profile image update

---

src/index.css

closes: #902 
https://github.com/narayan954/dummygram/assets/66116440/484c0cfd-e92b-4d45-a0a0-4ec620a82678

fixed nav icons color on hovering

---

src/App.jsx
src/components/Favorite.jsx
src/components/Post/PostNav.jsx
src/pages/Profile/index.css
src/pages/Profile/index.jsx

Hey @narayansoni I have made the changes that I stated in Issue #886.  Please review my or and merge it. Thank you!
1. Changes the color of scroll to top button.
2. Fixed profile picture size
3. Changed the favorites page

Made changes to scroll to top button, profile pircture and saved page

---

src/App.jsx
src/index.css
src/pages/Profile/index.css

Closes: #916 
| | |
|---|-----|
|Before|Updated|
| <img width="960" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/2cd8f4cb-b8ce-4733-ae62-7289b08d4981"> | <img width="960" alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/b17bf843-0ecc-4d54-b334-86a9c3a44c72"> |

fixed padding and scrolltotop button

---

src/components/Post/index.jsx
src/components/postView/index.jsx

Closes: #911 
| | |
|---|----|
|Before|Updated|
| <img width ="570" src="https://github.com/narayan954/dummygram/assets/66116440/1d8e51ef-0245-4eef-a388-aa7b4296c15b"> | <img width ="570" src="https://github.com/narayan954/dummygram/assets/66116440/539007fa-facb-431e-b094-c20d5aa2a01d"> |
|  <img width ="570" src="https://github.com/narayan954/dummygram/assets/66116440/3a32d47c-51cc-4eaf-8c3c-4879ae03abfb"> | <img width ="570" src="https://github.com/narayan954/dummygram/assets/66116440/9800662e-0d7b-41b2-9b64-bdcc5d99d011">|
| <img width ="550" src="https://github.com/narayan954/dummygram/assets/66116440/bd801031-e1d7-458e-8d4d-bc22403dbac7"> | <img width ="550" src="https://github.com/narayan954/dummygram/assets/66116440/a289379d-63c7-4632-9201-f5215a38eb2a">|

fixed padding around post captions

---

src/index.css
src/pages/Profile/index.jsx

Closes: #756 
https://github.com/narayan954/dummygram/assets/66116440/d9b9548b-c7fe-47ae-acb7-a38550439c7c

added profile image cancel btn

---

src/components/SideBar/Footer.jsx
src/components/SideBar/index.css

Closes #944 
Enhanced the footer by aligning the links and fixing it at the bottom as mentioned.
Kindly review and merge the pr

feat: footer modified

---

src/components/SettingsComponents/Sounds/index.css

This PR closes #779 
I have fixed the responsiveness of the page.

Sound page overlap fixed

---

src/components/SideBar/Footer.jsx
src/components/SideBar/index.css

Closes: #954 
- Added logos
- Fixed padding of footer links
- Fixed padding of sidebar for different screen sizes
- Different footer UI for different width of sidebar 
| Before  | Updated |
|---|----|
| <img alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/447f1790-bac0-4d14-a0b8-cb2b1d7f9471"> | <img alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/fb2f1655-90c2-4413-a3df-12805a26ee47">|
| <img alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/dd2a77f3-85d3-461f-8eb9-ad2157a2d463"> | <img alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/d176a82e-9140-4b0d-8a23-5f376eec6211">|

footer changes

---

src/components/Notification/index.jsx

This PR closes #1012 
Fix the dom validation error.

Fix notif page console error

---

src/components/Notification/index.jsx
src/pages/Profile/index.jsx

This PR closes #1019 
Fixed the highlight on notif page and also add the to attribute to the Link and updated it also on the profile page to include username as well.

Fix name highlight on notification page

---

src/components/CommunityChat/Reaction/index.css
src/components/CommunityChat/Reaction/index.jsx
src/components/CommunityChat/index.css
src/components/CommunityChat/index.jsx
src/index.css
src/reusableComponents/Darkmode/index.css

This PR closes #1033 
Added chat reaction feature.

Chat reaction

---

src/pages/Profile/feed/index.css

#1068  Changed the display property to grid and set the grid-template-columns to evenly divide the posts into three columns, improving the overall visual presentation, also changed prop background-size to object-fit

Profile page post img fix

---

src/components/postView/index.jsx

Image post not showing fix #1074

Fixing ImageSlider import path

---

src/App.jsx
src/components/Post/index.css
src/components/Suggestions/index.css
src/components/Suggestions/index.jsx
src/components/index.js
src/index.css
src/pages/Profile/index.jsx

This PR closes #860 
I have added user suggestion on the right side of page. On width greater than 1300 it appear on the right side but on less than 1300 it appears as a slider below the second post. 
It fetches 5 random user and by clicking on any of them it take you to their profile. 
Their is also a add friend button which first check if the friend request is already sent or not to show the text `Remove request` and `Add friend`
When the user click on the button the state get updated and the request is sent or removed. 
On below 1300 I have also provided to chevron buttons so that without using scrollbar user can move by clicking on them.
I have removed those buttons on the mobile view.

Suggestion

---

src/reusableComponents/ShareModal/index.css
src/reusableComponents/ShareModal/index.jsx

Fix logo on share modal

---

src/components/postView/index.jsx

Bug fix for issue number #1113

bug-fix-1113 Enter button

---

src/components/postView/index.jsx

bug fix for issue number #1114 
Emoji breaking

bug-fix-1114 Emoji issue 

---

src/components/SideBar/index.css
src/components/SideBar/index.jsx

This PR closes #1091 
Fixed hover on menu.

fixed menu icon hover

---

src/components/Post/index.jsx

Add message on zero likes

---

README.md

This PR closes #1117 
Now, the program images are aligned properly even in mobile view.

Fix program image alignment in README

---

src/components/EditProfile/index.css
src/components/EditProfile/index.jsx

Empty validation check for each field.
Error message highlighted below of each field.
required changes  done!!
@narayan954 Please look out this PR linked with issue #1147

validation added on edit profile section

---

src/pages/FooterPages/Feedback/index.css
src/pages/FooterPages/Feedback/index.jsx

This PR closes #939 
I fixed the alignment of feedback page and also setup the char limit for its inputs.

Feedback vertical alignment

---

src/components/Guest/GuestSignUpBtn/index.css
src/index.css

fixes [BUG] #1258 added background color to the button so content and button don't overlap

fixes #1258 signup button overflowing in mobile devices when guest user sign in

---

src/components/Navbar/index.css

Fixes #1270 
I was facing the alignment because of my OS which is Linux & I've fixed the search box issue.
@narayan954 Kindly merge the PR and label 'hacktoberfest-accepted'

fix: search box issue

---

src/components/Post/PostNav.jsx

fixed #1278 card content save icon overflow issue

fix: card save icon overflow issue (#1278)

---

src/components/ReadMore/index.css
src/components/ReadMore/index.jsx

fix: caption hiding behind image issue

---

src/components/SideBar/index.jsx

Fixes: #1308 
The issue was that user data is stored in session storage and the data remains there even after logout. So to fix the issue I am clearing the session storage after logout.

Fix: User data after logout

---

src/components/Suggestions/index.css

Close #1318
https://github.com/narayan954/dummygram/assets/114663382/a03fb68c-740b-400b-a1b2-5a975867bf38

fix: hovering

---

src/pages/Login/index.css

fix: login page responsive (#1321)

---

src/components/CommunityChat/index.css

fix: chat input position
