src/App.jsx
This came in late, but it was meant to be added to #14
=> feat: added loading animation for posts

package-lock.json, package.json, src/components/Post.jsx, src/index.css
##description
- Updated card UI
- Added some icons
=> Improve UI - for cards [fixes #33]

.github/workflows/deployreact.yml, .github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/greetings.yml
Peer dependencies were causing the installation to fail and that has been addressed.
The ERR_REQUIRE_ESM error in greeting got a temporary solution till an official one is available.[Link](https://github.com/vaadin/docs/commit/8a5def21c1eddf940f48829a6abc9260beaa7ae8)
I do not have a firebase service account to test the deployment :( 
but I'm confident it'll go through :+1:
=> FIx Github action failing

src/App.jsx
=> added load more posts on scroll

package-lock.json, package.json, src/App.jsx, src/components/ImgUpload.jsx, src/components/SnackBar.jsx, src/main.jsx
- I Pritam Kundu have worked for #51 
- Used Material UI to add Snackbar Component
- Added Snackbar to repalce browser alerts
- Log In
- Sign Up
- Image Upload Error
- Sign In Error
- Firebase Error
- Replaced all alerts and error messages and with Snackbar Notifications
- Logging In
- Logging Out
- Error Messages
- Creating Post
=> Added MUI alerts to replace browser alerts ⚠️

CNAME, src/App.jsx, src/components/ImgUpload.jsx, src/components/Post.jsx
=> like function implemented 

index.html, src/index.css, src/script.js
issue #31 
Added Dark Mode Feature with dark mode toggle button and dark Mode effects to the website.
=> Added dark mode feature

src/components/Post.jsx, src/components/ReadMore.jsx, src/index.css
1). Added Box Shadow Around Post Box.
2). Added Read More Feature in the post -> If the caption is long, the read more button will be displayed and if the user clicks on the read more button, the whole caption will be displayed.
3). Added Comment Icon.
4). On hovering the user profile, the circle turns black and the image scales up a little.
=> read more feature

src/index.css
closes #145 
- Added `overflow-x: hidden;` property to index.css file.
=> Responsiveness fixed.

src/pages/Login.jsx, src/pages/Signup.jsx
All codes remain the same. I just added Hide and show function.
=> issue #262 Added Password Hide and Show option

src/index.css
This pull request addresses the alignment and readability issues with comments in the "dummygram" project. The changes include the addition of the text-align: left; and word-break: break-word; properties to ensure proper alignment and word wrapping for comments.
By applying these CSS properties, comments will now be left-aligned, resulting in a more consistent and visually appealing layout. Additionally, the word-break property ensures that long words or URLs within comments will be correctly wrapped to prevent overflow and maintain readability.
updated comment section
=> fixed comment alignment

src/components/Post.jsx
This PR contains the following changes:
- instead of view all comments, show something like "view all 123 comments" or "view 1 comment" in case of comments.
- in case without comment, "disable the button" and show something like "no comments yet".
- in case without comment show something like "be the first one to comment" placeholder on input fields of comment.
- Changed the font color of the disabled button to #616161 since the default font color was hard to see/read in  disabled state
Screenshots:
=> Issue#371 - Show no. of comments in the post

src/App.jsx
- This PR is intended for the close icon button on the upload post pop-up.
- Added cursor: pointer inline style with code linting principles.
-  Showing cursor as pointer on hovering on close icon of upload post pop-up so the user can know it's clickable
- This PR fixed this ISSUE:#393
=> Issue#393 - Showing cursor as pointer on hovering on close icon of upload post pop-up

src/components/Post.jsx, src/index.css, src/pages/Profile.jsx
Solved issues in pr #394. @narayansoni  can you review the changes
=> edit profile pic feature added 

src/components/Post.jsx, src/pages/Profile.jsx
Added save your favourite post option 
For that i have stored the id and post to the localstorage and when the user checks his profile he can see his saved posts.
=> Added save favourite option

src/pages/Login.jsx
=> issue#277 Alert updated

src/pages/Profile/index.jsx
This PR fixes #578. 
Changes:
1. Email will be displayed only in current user's profile page 
2. email will be set to empty string when its not current user.
=> Fix email issue

src/App.jsx, src/components/SideBar/Footer.jsx, src/pages/About/index.css, src/pages/About/index.jsx, src/pages/index.js
This PR closes issue no. #552 
I have dynamically added data of number of forks and stars but unable to do the same for number of commits. When I tried to fetch total commits, it only gave me 28 rather than all. I tried some solutions but according to me there is a need of access token by the owner.
=> Create about page for dummygram

src/components/ImgUpload/index.jsx
This PR fixes issue no. #649 
It was somewhat tricky to find but, very crucial to implement. Everything was working fine with the user collection but, whenever the user create a new post his/her data in the collection got replaced with an array that contain just a ref for a single post.
Actually, there was a mistake in updating the doc. Instead of updating doc, it was getting replaced by the set function.
=> Fix data lose that was happening due to creating post

src/index.css, src/pages/Login/index.css, src/pages/Login/index.jsx
Closes #652 as per the changes mentioned in the issue section
Modified the forgot password and sign in links by changing the font size and adding hovering effects.
=> Chnges made as per mentioned

src/components/SideBar/index.jsx
This pull request fixes a bug that causes a "Cannot read properties of null (reading 'photoURL')" error in the code. The error occurs when the user object is null or undefined, and the code tries to access the photoURL property.
Added a conditional check to verify if the user object exists before accessing the photoURL property.
=> Bug Fix: Fix "Cannot read properties of null (reading 'photoURL')" error

src/pages/Profile/index.jsx
This pull request fixes errors (#725) cannot read properties of null of displayName, uid. The error occurs when the user object or auth  is still  null or undefined, and the code tries to access the displayName & uid  property.
##Changes Made
1.Added optional chaining before accessing displayName.
2.Added conditional check in useEffect to make sure auth.currentUser it's not null.
3.Removed unnecessary useEffect
```javascript
useEffect(() => {
if (auth.currentUser) {
setUser(auth.currentUser);
} else {
navigate("/dummygram/login");
}
}, []);
```
because was doing the same thing like below useEffect (which this handles much better the auth state changes)
```javascript
useEffect(() => {
const unsubscribe = auth.onAuthStateChanged((authUser) => {
if (authUser) {
setUser(authUser); …
```
=> BugFix on Profile Page

src/pages/FooterPages/About/index.css, src/pages/FooterPages/About/index.jsx, src/pages/FooterPages/ContributorPage/index.jsx, src/pages/FooterPages/Guidelines/index.jsx, src/pages/NotFound.jsx
ABOUT PAGE 
CONTRIBUTOR PAGE
HELP PAGE
GUIDELINES/POLICY PAGE
All buttons route back to the home page.
=> Routing home buttons

src/components/ImgUpload/index.jsx, src/components/Post/CommentBox.jsx, src/components/SideBar/index.jsx, src/pages/Login/index.jsx, src/pages/Signup/index.jsx, src/reusableComponents/Auth/Auth__pass__input.jsx, src/reusableComponents/Auth/Auth__text__input.jsx
This PR closes issue no. #781 
I have added char limit on email, name ,comments and caption. I was not able to find any other. I thought of adding it on password but, it doesn't made much sense to me.
=> Add char limit on different input fields

src/components/SearchBar/index.css, src/components/SearchBar/index.jsx
Improved Search bar section by added some CSS properties on it to look it good.
Add search icon embedded on search bar
Make it responsive in all devices.
@narayan954 issue #791 resolved please check it !!
=> Improved UI of search bar for search page

src/components/ImgUpload/Camera/index.css, src/components/ImgUpload/Camera/index.jsx, src/components/ImgUpload/index.css, src/components/Navbar/index.css, src/components/Navbar/index.jsx, src/components/Post/index.jsx, src/components/SearchBar/index.css, src/components/SettingsComponents/Sidebar/index.css, src/components/SettingsComponents/Sidebar/index.jsx, src/components/SettingsComponents/Sounds/index.css, src/components/SideBar/index.css, src/index.css, src/pages/FooterPages/design.css, src/pages/Profile/index.css, src/reusableComponents/ErrorBoundary/index.css, src/reusableComponents/ShareModal/index.css
#818 Change theme color
close #818 
In this I am change the whole theme color of app .
also solve minor bug that is soundsetting route and apply active tab CSS in setting page.
I think you loved this theme.
=> [FEATURE] Change theme color

src/App.jsx, src/components/ImgUpload/index.jsx, src/components/Post/PostHeader.jsx, src/components/Post/PostNav.jsx, src/components/SideBar/index.jsx, src/index.css, src/pages/PostView/PostViewStyled.jsx, src/pages/Profile/index.jsx, src/reusableComponents/Logo/index.jsx
This PR closes issue no. #556 
Initially, I was going to dynamically fetch data for post header but I found that it will take too many requests. I mean a seperate request for every post and whenever the home page re-render it fetches again.
So, instead I added static data and in the profile page whenever the user update image then, I made it so that the all posts image also get updated. Along with that I saw that image in the users collection was not getting updated so, I also updated that.
In addition to all this, I also did some other changes, such as dynamically rendering routes for user profile. So, before the url was:
`/dummygram/profile` and it was using some states to check whether it current user or not. Instead I made the url this:
`/dummygram/:username` Hence, we don't need to …
=> Old Post image updation

README.md
=> Toggle added in contributors section

src/components/CommunityChat/index.css
css alignment issue for chat section bug number #895 
before :- 
After :-
=> bug fix for chat css alignment #895

src/components/Post/PostHeader.jsx, src/components/ProfileDialogBox/index.css, src/components/ProfileDialogBox/index.jsx
Closes: #952 
- Changed UI of profile dialog box
- Removed dummy data and displayed user data if present
- fixed image
|||
|---|----|
|Before|After|
|<img alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/438cd642-ba88-4e32-a1c4-67cf47708843">|<img alt="image" src="https://github.com/narayan954/dummygram/assets/66116440/7baac538-2997-4a28-b5e2-40ba964166e1">|
=> profile dialog box ui and dummy data

src/components/ImgUpload/index.jsx, src/components/Post/CommentDialogBox.jsx, src/components/Post/index.jsx, src/components/SideBar/index.css, src/components/SideBar/index.jsx, src/pages/Profile/index.jsx
This PR closes #1017 
I have added a dropdown list and also made it darkmode compatible. It works fine. I haven't dynamically added the name of user in the sidebar and replaced it with `Me` because whenever the page loads it take time to fetch user data. which result in delay in showing the name which doesn't look good.
=> Add dropdown menu in sidebar

src/components/EditProfile/index.jsx, src/pages/Signup/index.jsx
This PR closes #1020 
I have altered the regex to include only small case letter and also increased the length for username to 20. I also changed a method on signup page to check if the username exists or not.
=> Update username regex

src/components/CommunityChat/index.jsx, src/pages/Profile/feed/index.jsx, src/pages/Profile/index.jsx
This PR closes #1021 
I have update the feed to fetch data based on timestamp.
=> Profile feed time

src/components/Post/PostHeader.jsx
This PR closes #1063 
Used db transaction for the cleanup of post deletion.
=> Use db transaction for post cleanup

src/App.jsx
This PR closes #1142 
Fixed the memory leaking. The event listener was not remove correctly from the useEffect as they have give name of the constant instead of the function and I think window.addEventListenere doesn't return anything. So, the constant become undefined.
=> Fix event listener leaking

src/components/EditProfile/index.jsx, src/components/SideBar/index.jsx
- **Added Margin Right Property to Logout Button to Solved Gap Issues Between Logout and Cancel Buttons on Logout Dialogue Box.**
- **I wrote Comment that Code Line.**
=> fix: Added Margin Property to resolved Gap between Buttons

package.json, src/App.jsx, src/index.css, src/pages/Signup/index.css, src/pages/Signup/index.jsx, src/reusableComponents/Auth/Auth__ctn__group.jsx, src/reusableComponents/Auth/index.css
This PR addresses #1003.
I have fixed the text color in the dark mode and is now visible. Also the margin issue has been fixed and sign up form styling is fixed and looks exactly like login form.
|![Screenshot from 2023-08-21 16-05-05](https://github.com/narayan954/dummygram/assets/56023604/e3e9d8f0-5650-49c3-be69-b1bb17c076ee)|![Signup-1](https://github.com/narayan954/dummygram/assets/56023604/9817b589-913f-4865-b1c8-b894aab94c35)|![Signup-2](https://github.com/narayan954/dummygram/assets/56023604/16c3a5e7-fec9-4d22-8258-ddd00bcdeffd)|
|-|-|-|
=> Fix login and signup page styling

src/components/CommunityChat/index.css, src/index.css
Closes: #1264
This PR realigns scroll top icon to prevent chat messages from overlapping, improving the layout design.
=> Realign scroll top

src/index.css, src/pages/Login/index.css, src/pages/Signup/index.css, src/pages/Signup/index.jsx
fixes singup page profile picture is overflowing this is fixed in #1268
=> fixes singup page overflow issue

src/components/ReadMore/index.jsx
Removed semi colon at comments in the Comment Dialog box
=> fix: semicolon added on every comment (#1266)

src/components/Post/CommentDialogBox.jsx, src/js/postFn.js
Fix the issue in deleting the comments: Basically when we delete the comment every time the last comment is deleted because when we use closure during the map it always takes the comment value that is the last one and always the last element it passes to deleteComment() function. 
So I use one separate state that contains the id of a particular comment when it's deletion call.
=> Fix the issue while deleting the comments.

src/reusableComponents/Auth/index.css
=> Fixed the alignment of auth page
